---
title: "BSE658A-Summary-05"
author: "Abin Thomas (Roll No. 21218261)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


```{r}
library(lsr)
library(tidyverse)
path <- "D:/Abin/Documents/BSE658A_BioStats/BSE658A-Assignments/kc_house_data.csv"
kc_housesales_data <- read.csv(path)
#kc_housesales_data
```

```{r}
hsdtibble <- as_tibble(kc_housesales_data)
#hsdtibble
```


```{r}
df <- data.frame(hsdtibble$sqft_living)

ggplot(df, aes(x = hsdtibble$sqft_living)) + geom_histogram(bins=12)
```

```{r}
library(psych)
#to find skewness of the data
skew(hsdtibble$sqft_living)
```
```{r}
#Measures of Central Tendency

mean(hsdtibble$sqft_living)
median(hsdtibble$sqft_living)
modeOf(hsdtibble$sqft_living)
maxFreq(hsdtibble$sqft_living)
```
```{r}
#Measures of variability
library(dplyr)
df <- mutate(df, housenumber= 1:length(hsdtibble$sqft_living))
ggplot(df, aes(y = hsdtibble$sqft_living, x = housenumber)) + geom_point()
```

```{r}
range(hsdtibble$sqft_living)
```
```{r}
#iqr
quantile(x = hsdtibble$sqft_living, probs = c(.25,.75)) #second 
```
```{r}
#variance
var(hsdtibble$sqft_living)
sd(hsdtibble$sqft_living)
```

```{r}
#let's check if bessel's correction makes a difference

sdn <- function(x) {
  return(sqrt(mean((x - mean(x))^2)))
}
sdn(hsdtibble$sqft_living)
```
```{r}
summary(hsdtibble$sqft_living)
```

```{r}
#boxplot?
ggplot(df, aes(x=hsdtibble$sqft_living, )) + 
  geom_boxplot()+ coord_flip()
```
```{r}
#let's try the summary of whole dataset
summary(hsdtibble)
```
```{r}
describe(hsdtibble)
```

```{r}
library(dplyr)
samplesz = c(1:2000)
sno = c(1:length(samplesz))
sz = as_tibble_col(sno,column_name = "Sample Number")
sz <- mutate(sz,'Sample Size' = samplesz)
#sz
```
```{r}
#samples = tibble()
#for (i in sz$`Sample Size`) {
#  samplesi <- sample_n(hsdtibble,i)
#}
```


```{r}
smean = c()
samsd = c()
for (i in sz$`Sample Size`) {
  sampled = (sample_n(hsdtibble,i))
  smean1 <- mean(sampled$sqft_living)
  smean = c(smean,smean1)
  samsd1 <- sd(sampled$sqft_living)
  samsd = c(samsd,samsd1)
}
```



```{r}
Rsampletib <- sz %>% mutate('Sample Mean' = smean )
Popmean = c(rep(mean(hsdtibble$sqft_living),length(sno)))
Rsampletib <- Rsampletib %>% mutate('Population Mean' = Popmean )
Rsampletib

```

```{r}
#samsd = c()
#for (i in sz$`Sample Size`) {
#  samsd1 <- sd((sample_n(hsdtibble,i))$sqft_living)
#  samsd = c(samsd,samsd1)
#}
```

```{r}
Rsampletib <- Rsampletib %>% mutate('Sample Standard Deviation' = samsd )
Popsd = c(rep(sd(hsdtibble$sqft_living),length(sno)))
Rsampletib <- Rsampletib %>% mutate('Population Standard Deviation' = Popsd )
Rsampletib
```


```{r}
df1 <- data.frame(Rsampletib$`Sample Mean`)
df1 <- mutate(df1,`Sample Size`= 1:length(Rsampletib$`Sample Size`))
ggplot(df1, aes(y = Rsampletib$`Sample Mean`, x = Rsampletib$`Sample Size`)) + geom_point() + geom_hline(yintercept=mean(hsdtibble$sqft_living), linetype="dashed", color = "red",size = 1) + labs(x = "Sample Size(No. of houses randomly selected)",y = "Sample Mean(Average Living Room Size of Sample)") + 
 geom_text(aes( 1400, 2500, label = "Population Mean(Average Living Room Size of Population)"),colour = "red", size = 4,show.legend = FALSE,check_overlap = TRUE)
```

```{r}
df2 <- data.frame(Rsampletib$`Sample Standard Deviation`)
df2 <- mutate(df2,`Sample Size`= 1:length(Rsampletib$`Sample Size`))
ggplot(df2, aes(y = Rsampletib$`Sample Standard Deviation`, x = Rsampletib$`Sample Size`)) + geom_point(na.rm = TRUE) + geom_hline(yintercept=sd(hsdtibble$sqft_living), linetype="dashed", color = "red",size = 1) + labs(x = "Sample Size(No. of houses randomly selected)",y = "Sample Standard Deviation") + 
 geom_text(aes( 1700, 1200, label = "Population Standard Deviation"),colour = "red", size = 4,show.legend = FALSE,check_overlap = TRUE)
```